### PR TITLE
Update domoticz.py

### PR DESCRIPTION
**Pull request by rbroeders**
Support for "long press release" on Aqara wireless button (small square one with round button). Value 4 never happens.
see https://www.domoticz.com/forum/viewtopic.php?f=68&t=27454&start=20

### CODE REVIEW

**Comment by pipiche38** [comment]
Thank you very much for this PR. Would you mind to rebuild it against the beta branch instead of the stable one ?
So that we validate that there is no side effects (like value 255 was not managed until now, and we will report it). And today the SwitchAQ2 type is used by several model of Aqara switches

**Comment by rbroeders** [comment]
No problem, just did so.
I also ordered the Aqara wireless switch (the big one with two buttons), when I receive it (within a few weeks) I will also test that one.
I already tested with the Aqara wall switch but it doesn't support that event unless I can configure it to work without the physical switch. But that can only be done with Mi Home app and after unpairing with Xiaomi it looses that setting. (Would be a nice feature if you can implement that setting)

**Comment by pipiche38** [comment]
I suggest to close this PR. 
For the Aqara wireless switch, let's use the Forum. or you can also reach me on Keybase.io for instant messaging ( @pipiche ), but I think it should be supported : https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Compatible-Devices.md#xiaomi

**Comment by rbroeders** [comment]
I think so too, but I want to make sure that all evens are handled by the plugin. I'll contact you when needed.
Thanks again for your help :)

**Pull request closed without merging**
