### PR TITLE
Using Type from config file instead of model name

### PR DESCRIPTION
**Pull request by mitkodotcom**
Using Type from config file instead of model name

### CODE REVIEW

**Comment by pipiche38** [comment]
Could you clarify what is the difference ? There is a unique reelation between the ThermoMode_6 and this Device Model, so I do not see why in one case it doesn't work and in the other case it does work

please also use elif instead of if

**Comment by mitkodotcom** [comment]
All receive_* functions are called from tuya_eTRV_response() 

In tuya_eTRV_response()  you have

 model_target = eTRV_MODELS[_ModelName]
 
 In eTRV_MODELS you have
 
     "TS0601-_TZE200_dzuqwsyg": "TS0601-thermostat",
     
 When _ModelName is "TS0601-_TZE200_dzuqwsyg", then model_target has a value of "TS0601-thermostat"
 
 So 

if model_target in ["TS0601-_TZE200_dzuqwsyg", ] 

will never match. The variable model_target will never have a value of  "TS0601-_TZE200_dzuqwsyg", because it is set from the array of eTRV_MODELS to "TS0601-thermostat"
 
 You are right that there is a relation between the device model and thermo mode, but this exact device model name is not accessible within the receive_* functions because the variable 'model_target' is populated with another value - a more generic one.
 
 About if and elif - its the way it should be. You just can't see it until apply the patch. The if condition ("TS0601-thermostat") is now moved down as elif, because otherwise it will always match - when mode is ThermoMode_6, model_target is "TS0601-thermostat", so the order matters and you should check the type first. The real code is as follows:
 
     # Update ThermoOnOff widget ( 6501 )
    if re.search('/ThermoMode_6/',self.ListOfDevices[NwkId]["Ep"][srcEp]["Type"]):
        if data == "00":
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 0, Attribute_="6501")  # ThermoOnOff to Off
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 0, Attribute_="001c")  # ThermoMode_6 to Off

        else:
            checkAndStoreAttributeValue(self, NwkId, "01", "0201", "6501", "On")
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 1, Attribute_="6501")  # ThermoOnOff to On
            # Let's check what Mode we are 
            mode = get_tuya_attribute( self, NwkId, "ManualMode")
            if mode == "00":
                # Cooling
                MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 1, Attribute_="001c")  # ThermoMode_6 to Cool
            elif mode == "01":
                # Heating
                MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 2, Attribute_="001c")  # ThermoMode_6 to Heat
            elif mode == "02":
                # Fan
                MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 3, Attribute_="001c")  # ThermoMode_6 to Fan

    elif model_target in ["TS0601-thermostat", "TS0601-eTRV3", ]:
        store_tuya_attribute(self, NwkId, "Switch", data)
        if data == "00":
            checkAndStoreAttributeValue(self, NwkId, "01", "0201", "6501", "Off")
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 0, Attribute_="6501")  # ThermoOnOff to Off
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 0, Attribute_="001c")  # ThermoMode_2 to Off
        else:
            checkAndStoreAttributeValue(self, NwkId, "01", "0201", "6501", "On")
            MajDomoDevice(self, Devices, NwkId, srcEp, "0201", 1, Attribute_="6501")  # ThermoOnOff to On

    else:
        checkAndStoreAttributeValue(self, NwkId, "01", "0201", "6501", data)

**Comment by mitkodotcom** [comment]
Also, this way there is consistency with Modules/command.py - the selection there is by DeviceType, although the _model_name is also used. You may consider "if DeviceType == "ThermoMode_6" instead of "if _model_name in ( "TS0601-_TZE200_dzuqwsyg", )" there. The same DeviceType (selector for Cool/Heat/Fan) may be used by other devices and manufacturers in the future. When two devices have the same DeviceType, they most probably will be processed equally both in domoticz-to-device direction (command.py) and device-to-domoticz direction (tuyaTRV.py). This way creating a new config file and probably new element in eTRV_MODELS will be sufficient for adding the new device. Less work in the future.

**Comment by pipiche38** [comment]
This make sense. However I think this is not coherent with the rest, and I think the mistake is more that we are trying to map this device with a Thermostat one , instead of creating a new one like Thermostat-Coil-Fan

**Comment by mitkodotcom** [comment]
Adding TS0601-thermostat-Coil is fine, but you should add it in many places then. Please add it also to  receive_setpoint. Change

    if model_target in[ "TS0601-thermostat","TS0601-_TZE200_b6wax7g0"] :
    
to

    if model_target in[ "TS0601-thermostat","TS0601-_TZE200_b6wax7g0", "TS0601-thermostat-Coil"] :
    
Except the setpoint, everything else is working now.

**Comment by pipiche38** [comment]
I’ll have a look later, but my understanding is that model_target is based on ´Model’ attribute in opposition of what get_model does.

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
I suggest to close that one as the PR addressing the Thermostat Coil Fan is addressed here #1202

**Comment by pipiche38** [comment]
Thanks for submiting

**Pull request closed without merging**
