### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/Domoticz-Zigate/actions

Python linters like flake8 and pylint do not like variables that are used but never defined or imported.  This is the issue that I am trying to address in the Domoticz repo.

### CODE REVIEW

**Comment by cclauss** [comment]
```
./Tools/SerialLink.py:585:19: E999 SyntaxError: invalid syntax
            print "Node Version: 0x%08x" % self.GetVersion()
```
`print()` is a function in Python 3.

**Comment by pipiche38** [comment]
Thanks and I do understand , and that is really great. This will also remove also the issue reported by Visual Studio.
So I'm more than  welcome to go forward, but when I tried it, I got the I reported https://github.com/domoticz/domoticz/pull/4720#issuecomment-796818879 and which prevent the run of the plugin

**Comment by pipiche38** [comment]
Can we schedule the GitHub action on the 'beta' branch instead of the stable (default) ?

**Comment by cclauss** [comment]
Once it is landed, it will run on all branches.

The latest commit temporarily ignores `Devices` and `Parameters` so you can see what other _undefined names_ flake8 can find.

**Comment by pipiche38** [comment]
Oki, let's give a try and see the amount

**Comment by pipiche38** [comment]
@cclauss thanks so much for taking the freedom to propose this PR.

**Comment by pipiche38** [comment]
@cclauss I saw that your PR has finaly been approved on domoticz, this great.

The only limitation that I see, is the PR is on the development branch of Domotciz and will take time that users are moving to the latest version including your PR.

As the Domoticz-Zigate plugin must be compatible with all domoticz version, do you see if 

using a try clause is possible ?

```
try:
    from Domoticz import Devices, Parameters
Except:
   pass
```

**Comment by cclauss** [comment]
You do not need the try / except...  Just do.
`from Domoticz import Devices, Parameters`

Domoticz will always create those for your plugin.

**Comment by cclauss** [comment]
Bare `except` is a bad idea... https://realpython.com/the-most-diabolical-python-antipattern/

**Comment by pipiche38** [comment]
Nope it won't work, because as stated quiet a large of users are still with an old version of Domoticz and the from Domoticz import Devices, Parameters will not work, only the import Domoticz will.

**Comment by cclauss** [comment]
What error message do you get with `from Domoticz import Devices, Parameters`

Does `Devices = Domoticz.Devices` work?  If not, what is error message?

What does `print(dir(Domoticz))` print?

**Comment by pipiche38** [comment]
This is what I already mentioned last time on the Domoticz PR.

From my point of view the Python Framework embedded into Domoticz is not able to handle that format. Only the 
`import Domoticz `works

if I add `from Domoticz import Devices, Parameters`then I'm getting this error message when starting the plugin from Domoticz

```
Mar 12 23:12:53 rasp domoticz[8287]: 2021-03-12 23:12:53.892  Status: Python Plugin System: (DIN ZiGate) Started.
Mar 12 23:12:54 rasp domoticz[8287]: 2021-03-12 23:12:54.117  Error: Python Plugin System: (Zigate) failed to load 'plugin.py', Python Path used was '/var/lib/domoticz/plugins/Domoticz-Zigate/:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/site-packages:/usr/lib/python3.8/site-packages'.
Mar 12 23:12:54 rasp domoticz[8287]: 2021-03-12 23:12:54.118  Error: Python Plugin System: (DIN ZiGate) Module Import failed, exception: 'ImportError'
Mar 12 23:12:54 rasp domoticz[8287]: 2021-03-12 23:12:54.118  Error: Python Plugin System: (DIN ZiGate) Module Import failed: ' Name: Domoticz'
Mar 12 23:12:54 rasp domoticz[8287]: 2021-03-12 23:12:54.118  Error: Python Plugin System: (DIN ZiGate) Error Line details not available.
```

**Comment by cclauss** [comment]
Can you please answer the other two questions?

**Comment by pipiche38** [comment]
What do you mean the 2 questions ? when I have the from/import statement the plugin doesn't start.

**Comment by cclauss** [comment]
1. What does `print(dir(Domoticz))` print?
2. Does `Devices = Domoticz.Devices` work?

**Comment by pipiche38** [comment]
`dir(Domoticz):  ['Configuration', 'Connection', 'Debug', 'Debugging', 'Device', 'Error', 'Heartbeat', 'Image', 'Log', 'Notifier', 'Status', 'Trace', '__doc__', '__loader__', '__name__', '__package__', '__spec__']`

> Mar 13 17:22:32 rasp domoticz[750]: 2021-03-13 17:22:32.951  Error: Python Plugin System: (DIN ZiGate) 'onStart' failed 'AttributeError':'module 'Domoticz' has no attribute 'Devices''.

**Comment by cclauss** [comment]
Thank you!  This is not what I was expecting!!

Can you please run this function inside a plugin so I can understand the Domoticz values?

Thanks much for your help.
```python
import inspect
import Domoticz

def inspect_Domoticz():
    print(Domoticz.__name__, Domoticz.__package__)
    for name, value in inspect.getmembers(Domoticz):
        if not name.startswith("_"):
            if callable(value):
                value = "callable"
            print("{{}} {} = {}".format(type(value), name, value))
```

**Comment by pipiche38** [comment]
```
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.846  Python Plugin System: (DIN ZiGate) Domoticz.__name__: >Domoticz< , Domoticz.__package__: ><
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.848  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Configuration
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Connection
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Debug
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Debugging
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Device
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Error
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Heartbeat
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.849  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Image
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.850  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Log
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.850  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Notifier
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.850  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Status
Mar 14 10:55:34 rasp domoticz[3064]: 2021-03-14 10:55:34.850  Python Plugin System: (DIN ZiGate) {} <class 'str'> = Trace
```

**Comment by cclauss** [comment]
Sorry...
Please change the last line to `print("({}) {} = {}".format(type(value), name, value))` which changes `{{}}` --> `({})`

**Comment by pipiche38** [comment]
```
 Domoticz.__name__: >Domoticz< , Domoticz.__package__: ><
 (<class 'str'>) Configuration = callable
 (<class 'str'>) Connection = callable
 (<class 'str'>) Debug = callable
 (<class 'str'>) Debugging = callable
 (<class 'str'>) Device = callable
 (<class 'str'>) Error = callable
 (<class 'str'>) Heartbeat = callable
 (<class 'str'>) Image = callable
 (<class 'str'>) Log = callable
 (<class 'str'>) Notifier = callable
 (<class 'str'>) Status = callable
 (<class 'str'>) Trace = callable
```

**Comment by pipiche38** [comment]
@cclauss as you can see 

`print(Domoticz.__name__, Domoticz.__package__)`

__package__ is empty

**Comment by cclauss** [comment]
```python
import inspect
import json
import Domoticz

def inspect_Domoticz():
    print(Domoticz.__name__)  # Domoticz.__package__ is ""
    for name, value in inspect.getmembers(Domoticz):
        if not name.startswith("_"):
            data_type = type(value)
            if callable(value):
                value = "callable"
            print("({}) {} = {}".format(data_type, name, value))

print("Devices: {}".format(json.dumps(Devices, indent=4)))
print("Images: {}".format(json.dumps(Images, indent=4)))
print("Parameters: {}".format(json.dumps(Parameters, indent=4)))
print("Settings: {}".format(json.dumps(Settings, indent=4)))
print(Domoticz.Status())
```

**Comment by pipiche38** [comment]
Here is the result (hope it helps )

```
 Domoticz
 (<class 'builtin_function_or_method'>) Configuration = callable
 (<class 'type'>) Connection = callable
 (<class 'builtin_function_or_method'>) Debug = callable
 (<class 'builtin_function_or_method'>) Debugging = callable
 (<class 'type'>) Device = callable
 (<class 'builtin_function_or_method'>) Error = callable
 (<class 'builtin_function_or_method'>) Heartbeat = callable
 (<class 'type'>) Image = callable
 (<class 'builtin_function_or_method'>) Log = callable
 (<class 'builtin_function_or_method'>) Notifier = callable
 (<class 'builtin_function_or_method'>) Status = callable
 (<class 'builtin_function_or_method'>) Trace = callable

```


 ```
Devices
 (<class 'dict'>) = {1: <Domoticz.Device object at 0xb0a74500>, 2: <Domoticz.Device object at 0xb0a74f20>, 3: <Domoticz.Device object at 0xb0a74f80>, 4: <Domoticz.Device object at 0xacad8020>, 5: <Domoticz.Device object at 0xacad8080>, 6: <Domoticz.Device object at 0xacad8140>}
 Images
 (<class 'dict'>) = {}
 Parameters
 (<class 'dict'>) = {'HardwareID': 10, 'HomeFolder': '/var/lib/domoticz/plugins/Domoticz-Zigate/', 'StartupFolder': '/usr/share/domoticz/beta-domoticz/bin/', 'UserDataFolder': '/var/lib/domoticz/', 'WebRoot': '', 'Database': '/var/lib/domoticz/domoticz.db', 'Language': 'fr', 'Version': '4.12', 'Author': 'zaraki673  pipiche38', 'Name': 'DIN ZiGate', 'Address': '0.0.0.0', 'Port': '9999', 'SerialPort': '/dev/serial/by-id/usb-FTDI_ZiGate_AC3JVNBY-if00-port0', 'Username': '', 'Password': '', 'Key': 'Zigate', 'Mode1': 'USB', 'Mode2': '', 'Mode3': 'True', 'Mode4': '9440', 'Mode5': '', 'Mode6': '2', 'DomoticzVersion': '2020.2 (build 13080)', 'DomoticzHash': '68b6cf7de-modified', 'DomoticzBuildTime': '2021-03-15 02:05:12'}
 Settings
 (<class 'dict'>) = {'DB_Version': '148', 'Title': 'Domoticz', 'LightHistoryDays': '30', 'MeterDividerEnergy': '1000', 'MeterDividerGas': '100', 'MeterDividerWater': '100', 'RandomTimerFrame': '15', 'ElectricVoltage': '230', 'CM113DisplayType': '0', '5MinuteHistoryDays': '1', 'SensorTimeout': '60', 'SensorTimeoutNotification': '0', 'UseAutoUpdate': '1', 'UseAutoBackup': '0', 'CostEnergy': '2149', 'CostEnergyT2': '2149', 'CostEnergyR1': '800', 'CostEnergyR2': '800', 'CostGas': '6218', 'CostWater': '16473', 'UseEmailInNotifications': '0', 'SendErrorNotifications': '0', 'EmailPort': '25', 'EmailAsAttachment': '0', 'DoorbellCommand': '0', 'SmartMeterType': '0', 'EnableTabLights': '1', 'EnableTabTemp': '1', 'EnableTabWeather': '1', 'EnableTabUtility': '1', 'EnableTabCustom': '0', 'EnableTabScenes': '0', 'EnableTabFloorplans': '0', 'NotificationSensorInterval': '43200', 'NotificationSwitchInterval': '0', 'RemoteSharedPort': '6144', 'Language': 'fr', 'DashboardType': '0', 'MobileType': '0', 'WindUnit': '0', 'TempUnit': '0', 'WeightUnit': '0', 'SecStatus': '0', 'SecOnDelay': '30', 'AuthenticationMethod': '0', 'ReleaseChannel': '0', 'RaspCamParams': '-w 800 -h 600 -t 1', 'UVCParams': '-S80 -B128 -C128 -G80 -x800 -y600 -q100', 'AcceptNewHardware': '1', 'ZWavePollInterval': '60', 'ZWaveEnableDebug': '0', 'ZWaveNetworkKey': '0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10', 'ZWaveEnableNightlyNetworkHeal': '0', 'BatteryLowNotification': '0', 'AllowWidgetOrdering': '1', 'ActiveTimerPlan': '0', 'HideDisabledHardwareSensors': '1', 'EnableEventScriptSystem': '1', 'EventSystemLogFullURL': '1', 'DisableDzVentsSystem': '0', 'DzVentsLogLevel': '3', 'LogEventScriptTrigger': '1', 'WebTheme': 'simple-gray', 'FloorplanPopupDelay': '750', 'FloorplanFullscreenMode': '0', 'FloorplanAnimateZoom': '1', 'FloorplanShowSensorValues': '1', 'FloorplanShowSwitchValues': '0', 'FloorplanShowSceneNames': '1', 'FloorplanRoomColour': 'Blue', 'FloorplanActiveOpacity': '25', 'FloorplanInactiveOpacity': '5', 'TempHome': '20', 'TempAway': '15', 'TempComfort': '22.0', 'DegreeDaysBaseTemperature': '18.0', 'HTTPURL': 'aHR0cHM6Ly93d3cuc29tZWdhdGV3YXkuY29tL3B1c2h1cmwucGhwP3VzZXJuYW1lPSNGSUVMRDEmcGFzc3dvcmQ9I0ZJRUxEMiZhcGlrZXk9I0ZJRUxEMyZmcm9tPSNGSUVMRDQmdG89I1RPJm1lc3NhZ2U9I01FU1NBR0U=', 'HTTPPostContentType': 'YXBwbGljYXRpb24vanNvbg==', 'ShowUpdateEffect': '0', 'ShortLogInterval': '5', 'SendErrorsAsNotification': '0', 'IFTTTEnabled': '0', 'EmailEnabled': '0', 'Location': '45.182479;5.721077', 'ClickatellEnabled': '0', 'ClickatellAPI': '0', 'ClickatellFrom': '0', 'ClickatellPassword': '0', 'ClickatellTo': '0', 'ClickatellUser': '0', 'EmailFrom': '0', 'EmailServer': '0', 'EmailTo': '0', 'EmailPassword': '0', 'EmailUsername': '0', 'GCMEnabled': '0', 'HTTPEnabled': '0', 'HTTPField1': '0', 'HTTPField2': '0', 'HTTPField3': '0', 'HTTPField4': '0', 'HTTPPostData': '0', 'HTTPPostHeaders': '0', 'HTTPTo': '0', 'KodiIPAddress': '224.0.0.1', 'KodiEnabled': '0', 'KodiPort': '9777', 'KodiTimeToLive': '5', 'LmsPlayerMac': '0', 'LmsDuration': '5', 'LmsEnabled': '0', 'ProwlAPI': '0', 'ProwlEnabled': '0', 'PushALotAPI': '0', 'PushALotEnabled': '0', 'PushbulletAPI': '0', 'PushbulletEnabled': '0', 'PushoverAPI': '0', 'PushoverUser': '0', 'PushoverEnabled': '0', 'PushsaferAPI': '0', 'PushsaferImage': '0', 'PushsaferEnabled': '0', 'TelegramAPI': '0', 'TelegramChat': '0', 'TelegramEnabled': '0', 'WebLocalNetworks': '127.0.0.*;10.0.0.*', 'WebRemoteProxyIPs': '0', 'SecPassword': 'xxxxxx', 'ProtectionPassword': 'xxxxxx', 'MyDomoticzUserId': '0', 'MyDomoticzSubsystems': '0', 'OneWireSensorPollPeriod': '0', 'OneWireSwitchPollPeriod': '0', 'IFTTTAPI': '0', 'FCMEnabled': '0', 'MaxElectricPower': '6000'}
```

**Comment by cclauss** [comment]
A few more commands...

**Comment by pipiche38** [comment]
updated

**Comment by cclauss** [comment]
The above changes should produce a more readable output.

To answer your original question...
```python
try:
    from Domoticz import Devices, Images, Parameters, Settings
except ImportError:
    pass
```

**Comment by cclauss** [comment]
Can you please run https://github.com/pipiche38/Domoticz-Zigate/pull/796#issuecomment-799621930 ?

**Comment by pipiche38** [comment]
```
Domoticz
 (<class 'builtin_function_or_method'>) Configuration = callable
(<class 'type'>) Connection = callable
(<class 'builtin_function_or_method'>) Debug = callable
 (<class 'builtin_function_or_method'>) Debugging = callable
 (<class 'type'>) Device = callable
 (<class 'builtin_function_or_method'>) Error = callable
(<class 'builtin_function_or_method'>) Heartbeat = callable
 (<class 'type'>) Image = callable
 (<class 'builtin_function_or_method'>) Log = callable
 (<class 'builtin_function_or_method'>) Notifier = callable
 (<class 'builtin_function_or_method'>) Status = callable
 (<class 'builtin_function_or_method'>) Trace = callable
 'onStart' failed 'TypeError'.
 ----> Line 1014 in '/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py', function onStart
 ----> Line 220 in '/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py', function onStart
 ----> Line 234 in '/usr/lib/python3.8/json/__init__.py', function dumps
 ----> Line 201 in '/usr/lib/python3.8/json/encoder.py', function encode
 ----> Line 431 in '/usr/lib/python3.8/json/encoder.py', function _iterencode
----> Line 405 in '/usr/lib/python3.8/json/encoder.py', function _iterencode_dict
 ----> Line 438 in '/usr/lib/python3.8/json/encoder.py', function _iterencode
 ----> Line 179 in '/usr/lib/python3.8/json/encoder.py', function default
```

**Pull request merged**
