### PR TITLE
Mise en place ReadAttributeRequest et Quelques MAJ sur les attributs dans les clusters + recup manufacture

### PR DESCRIPTION
**Pull request by Smanar**
Version propre de https://github.com/sasu-drooz/Domoticz-Zigate/pull/173

### CODE REVIEW

**Comment by Smanar** [comment]
Bon ca marche pour recuperer la manufacture lors de la creation de device.

**Comment by pipiche38** [comment]
Honestly I don't like the approach to have one common Read Attribute. We don't how it will go with other devices at the moment, and I do prefer to have a dedicated ReadAttribute by Cluster/Attribute . This will make the code a bit more clear when call ReatAttribute.

So renaming the readAttribute_Xiamlo into ReadAttribute_000C would be more in line. And so with the 0008 used for Profalux right now, and 000C for Xiaomi and eventually others

**Comment by Smanar** [comment]
But you will have 10 fonctions with exactly the same content.
And you can have same attributribute for different clusters so you will make
 ReadAttribute_0004_cluster001 and  ReadAttribute_0004_cluster004 ?

I don't see a big diffrence beetween
RequestClusterAttribute(key,'0004','0001')
and
RequestAttribute_0004_cluster001(key)

But you will have 1 fonction instead of 15, for me it's that having a code a bit more clear ^^.

**Comment by pipiche38** [comment]
I do insist. This much clear from reading, debuging and maintaining the code to have separate ReadAttribute function.
For now, we are talking about 2 which is not a big deal.

In addition, you are highlighting a serious issue which is that the DeviceConf.txt , present the Xiaomi plug 'lumi.plug':{'Ep':{'01':{'0006','000c'}},'Type':'Plug/PowerMeter'}, as a 1 EndPoint device. In reallity it is much more than that and your patch is using such information to find the Ep. Which I thing is a very good step, but will be incompatible with all system already installed.

Finally why not using the simple command 0x0042 in order to get all Node Descriptor information ?

**Comment by pipiche38** [comment]
It might be also good to do the Node Descriptor request as part of the on-boarding process and before the CreateDomoDevice() call, so the information we could collect would be then stored also on the Domoticz DB

**Comment by Smanar** [comment]
Already 3, you forget this one to have manufacture. And soon more to retreive bulb information, setting device like the sensor device http://faire-ca-soi-meme.fr/domotique/2018/09/03/test-xiaomi-aqara-vibration-sensor/ soon for legrand device, ect ... remember some attribute are Read and Write and used for setting.

My patch can use the good endpoint if the code have it, It parse all endpoints according to cluster to choose the good endpoint.

Nevermind, for the device direction, I m waiting your decision. For me the better is making a better deviceconf.txt file  https://github.com/sasu-drooz/Domoticz-Zigate/issues/148 and ofc a better management in code.

Wich one information you want from Node descriptor ?

**Comment by pipiche38** [comment]
@Smanar 

- As the Node Descriptor , I think that would be good to decode as much as we can 
Logical Type : End Device, Router could be interesting for further used ( Topology)
MAC Capability : And as we have already exchanged, I think this would be good to get decoded the bit field in order to have an easy access to the information.
Manufacturer Code:
- I suggest that we do the 0x0042 command as part of the Discovering device. It is may be good to do it when receiving 0x004d to start with 0x0042 and when in state 0x8042, we could go with 0x0045 ...
- For the others I don't know what are they.

**Pull request closed without merging**
