### PR TITLE
Rename existing TS0601 modelName into a defined one, and remove TS060…

### PR DESCRIPTION
**Pull request by pipiche38**
Purpose is when loading the list of devices, we check if we have any TS0601 model name. If the case exist then we renamed the model into the expected one and we avoid having TS0601 model name (which is removed)

The end result is any up coming pairing of TS0601 based device, will end up with a bad pairing as unknown devices with all necessary information instead of pairing as a Thermostat

### CODE REVIEW

**Comment by pipiche38** [comment]
@SylvainPer what do you think about that PR ?

**Comment by SylvainPer** [comment]
Looks good for me, I can make some test with fake database this weekend if you wish.

**Comment by pipiche38** [comment]
I need to fix a circular import

**Comment by pipiche38** [comment]
@SylvainPer  I did the refactor of Model handling in readCluster attribute 0x0005.

- [x] Tested with a TS0601 Siren and works fine.
- [x] Tested with a TS0601 Smart Air and works fine.

**Comment by pipiche38** [comment]
@SylvainPer I did few testing on my end, and especially checked the worst cases, and this sound good.. Let me know what you think and if you do some testing as well

**Comment by pipiche38** [comment]
Test by @jp-keros on Siren. All good

**Pull request merged**
