### PR TITLE
Update ZLinky Cluster 0xff66 in case of alarm for excess power

### PR DESCRIPTION
**Pull request by SylvainPer**
- update 0xff66/0x0005:0x0008 behavior
- remove check alarm from intensity for zlinky fw version up to 3

### CODE REVIEW

**Comment by SylvainPer** [comment]
Wait for test and excess power at home

**Comment by pipiche38** [comment]
If you have a user whom is used to the alarms based on the %, when he will update to firmware 3 he will loose this functionality.
I would suggest that you put a device parameter ( not a global one but a "Param" ) which then can enable or disable this feature. I leave the default to you.

**Comment by SylvainPer** [comment]
Ok, for now, I wait to test the modification, I didn't succeeded this
afternoon.

**Comment by SylvainPer** [comment]
Tests are not conclusive, even with an excess during more than one minute and the logo of excess on the linky, nothing received on ff66/0005.
Revert the modification (which was incomplete, modification needed for 3 phases)

**Comment by pipiche38** [comment]
un grand merci

**Pull request merged**
