### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by Smanar**
Les couleurs RGB fonctionnent a 100%.
Les couleurs CW/WW devrait fonctionner aussi, pas de lampes pr tester.
Regroupement des 3 devices en 1, au lieu de 1bp+1variateur+1color on a un seul device avec toutes les commandes, je viens d'en programmer un sur detecteur, c'est plus commode pour regler en meme temps couleur et puissance.

Pas trouve, si possible de memoriser la couleur, le level fct differement sur le dimmer et dans l'option couleur.

### CODE REVIEW

**Comment by Smanar** [comment]
Bon y a eu rattage (conflitcs) , code a voir sur le fork

**Comment by Smanar** [comment]
Bon y a eu rattage (conflitcs) , code a voir sur le fork

**Comment by pipiche38** [comment]
Smanar,

Voici ce que je trouve comme diff ? Et que je vais essayer de tester. Est-ce que cela te semble cohérent ?

diff --git a/plugin.py b/plugin.py
index b4e9983..6571f85 100644
--- a/plugin.py
+++ b/plugin.py
@@ -186,63 +186,68 @@ class BasePlugin:
                                EPout=tmpEp

                #Disable on/off for other device than switch
-               #Disabled for color control because it may induce flashing on bulb (With rgb command in same time than color control)
+               if (Dtypename != "Switch") and (Command == "On"):
+                       Command = "Set Level"
+                       Level = 100
+               if (Dtypename != "Switch") and (Command == "Off"):
+                       Command = "Set Level"
+                       Level = 0
+
                if Command == "On" :
-                       if Dtypename == "Switch" :
-                               sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "01")
-                               UpdateDevice_v2(Unit, 1, "On",DOptions, SignalLevel)
-                       elif (Dtypename == "LvlControl"):
-                               Command = "Set Level"
-                               Level = 100
+                       sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "01")
+                       if Dtypename == "LvlControl" and DSwitchtype == "16" :
+                               UpdateDevice_v2(Unit, 1, "100",DOptions, SignalLevel)
                        else :
-                               pass
-                               #Do nothing for other
+                               UpdateDevice_v2(Unit, 1, "On",DOptions, SignalLevel)

                if Command == "Off" :
-                       if Dtypename == "Switch" :
-                               sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "00")
-                               UpdateDevice_v2(Unit, 0, "Off",DOptions, SignalLevel)
-                       elif (Dtypename == "LvlControl") :
-                               Command = "Set Level"
-                               Level = 0
+                       sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "00")
+                       if Dtypename == "LvlControl" and DSwitchtype == "16" :
+                               UpdateDevice_v2(Unit, 0, "0",DOptions, SignalLevel)
                        else:
-                               pass
-                               #Do nothing for other
+                               UpdateDevice_v2(Unit, 0, "Off",DOptions, SignalLevel)

                if Command == "Set Level" :
-                       if Dtypename == "LvlControl":
+                       if Dtypename == "LvlControl" and DSwitchtype == "16" :
                                self.ListOfDevices[Devices[Unit].DeviceID]['Heartbeat'] = 0  # As we update the Device, let's restart and do the next pool in 5'
+                               if Level == 0 :
+                                       sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "00")
+                                       UpdateDevice_v2(Unit, 0, "0",DOptions, SignalLevel)
+                               if Level == 100 :
+                                       value=returnlen(2,hex(round(Level*255/100))[2:])
+                                       sendZigateCmd("0081","02" + Devices[Unit].DeviceID + EPin + EPout + "00" + value + "0010")
+                                       UpdateDevice_v2(Unit, 1, "100",DOptions, SignalLevel)
+                               else :
+                                       value=returnlen(2,hex(round(Level*255/100))[2:])
+                                       sendZigateCmd("0081","02" + Devices[Unit].DeviceID + EPin + EPout + "00" + value + "0010")
+                                       UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)

-                               value=returnlen(2,hex(round(Level*255/100))[2:])
-                               sendZigateCmd("0081","02" + Devices[Unit].DeviceID + EPin + EPout + "00" + value + "0010")
+               if Dtypename == "ColorControl" :
+                       #With level
+                       if Hue == "" :
+                               Domoticz.Debug("onCommand - ColorControl - Level = " + str(Level) )
+                               #Grosse bidouille en provisoire, convertion du level en couleur XY
+                               Level_xy = Level * 42949672
+                               strxy = returnlen(8,hex(Level_xy)[2:])
+
+                               sendZigateCmd("00B7","02" + Devices[Unit].DeviceID + EPin + EPout + strxy + "00")
                                UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)
+                       #with Hue
+                       else :
+                               Domoticz.Debug("onCommand - ColorControl - Hue = " + str(Hue) )
+                               Domoticz.Debug("TODO !!!")

-                       if Dtypename == "ColorControl" :
-                               #With level
-                               if Hue == "" :
-                                       Domoticz.Debug("onCommand - ColorControl - Level = " + str(Level) )
-
-                                       #Grosse bidouille en provisoire, convertion du level en couleur XY
-                                       Level_xy = Level * 42949672
-                                       strxy = returnlen(8,hex(Level_xy)[2:])
-
-                                       sendZigateCmd("00B7","02" + Devices[Unit].DeviceID + EPin + EPout + strxy + "00")
-                                       UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)
-                               #with Hue
-                               else :
-                                       Domoticz.Debug("onCommand - ColorControl - Hue = " + str(Hue) )
-                                       Domoticz.Debug("TODO !!!")

                if Command == "Set Color" :
                        if Dtypename == "ColorControl" :
                                if Hue:
                                        Domoticz.Debug("onCommand - Set Color - Hue = " + str(Hue) )
-
+
                                        def hex_to_rgb(h):
                                                ''' convert hex color to rgb tuple '''
                                                h = h.strip('#')
                                                return tuple(int(h[i:i+2], 16)/255 for i in (0, 2 ,4))
-
+
                                        def rgb_to_xy(rgb):
                                                ''' convert rgb tuple to xy tuple '''
                                                red, green, blue = rgb
@@ -258,54 +263,28 @@ class BasePlugin:
                                                        cx = X / (X + Y + Z)
                                                        cy = Y / (X + Y + Z)
                                                return (cx, cy)
-
+
                                        def hex_to_xy(h):
                                                ''' convert hex color to xy tuple '''
                                                return rgb_to_xy(hex_to_rgb(h))
-
-                                       if Hue['m'] == 2:#CW WW mode
-
-                                               ww = int(Hue['ww'])
-                                               cw = int(Hue['cw'])
-
-                                               #Need to find convertion
-                                               strTemp = 0
-
-                                               sendZigateCmd("00B7","02" + Devices[Unit].DeviceID + EPin + EPout + strTemp + "00")
-                                               UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)
-
-
-                                       elif Hue['m'] == 3:#RGB mode
-                                               x, y = rgb_to_xy((int(Hue['r']),int(Hue['g']),int(Hue['b'])))
-
-                                               #Convert 0>1 to 0>FFFF
+
+                                       x, y = rgb_to_xy((int(Hue['r']),int(Hue['g']),int(Hue['b'])))
+
+                                       #With that x, y can be integer 0-65536 or float 0-1.0
+                                       if isinstance(x, float) and x <= 1:
                                                x = int(x*65536)
+                                       if isinstance(y, float) and y <= 1:
                                                y = int(y*65536)
-
-                                               strxy = returnlen(4,hex(x)[2:]) + returnlen(4,hex(y)[2:])
-                                               Level = int(strxy,16) / 42949672
-
-                                               sendZigateCmd("00B7","02" + Devices[Unit].DeviceID + EPin + EPout + strxy + "00")
-                                               UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)
-
+
+                                       strxy = returnlen(4,hex(x)[2:]) + returnlen(4,hex(y)[2:])
+                                       Level = int(strxy,16) / 42949672
+
+                                       sendZigateCmd("00B7","02" + Devices[Unit].DeviceID + EPin + EPout + strxy + "00")
+                                       UpdateDevice_v2(Unit, 2, str(Level) ,DOptions, SignalLevel)
                                else:
                                        Domoticz.Debug("onCommand - Set Color - Hue = " + str(Hue) )
                                        Domoticz.Debug("TODO !!!")

-
-#                      if Dtypename == "LvlControl" and DSwitchtype != "16" : # Old behaviour
-#                              if Level == 0 :
-#                                      sendZigateCmd("0092","02" + Devices[Unit].DeviceID + EPin + EPout + "00")
-#                                      UpdateDevice_v2(Unit, 0, "Off",DOptions, SignalLevel)
-#                              if Level == 100 :
-#                                      value=returnlen(2,hex(round(Level*255/100))[2:])
-#                                      sendZigateCmd("0081","02" + Devices[Unit].DeviceID + EPin + EPout + "00" + value + "0010")
-#                                      UpdateDevice_v2(Unit, 1, "On",DOptions, SignalLevel)
-#                              else :
-#                                      value=returnlen(2,hex(round(Level*255/100))[2:])
-#                                      sendZigateCmd("0081","02" + Devices[Unit].DeviceID + EPin + EPout + "00" + value + "0010")
-#                                      UpdateDevice_v2(Unit, 1, str(Level) ,DOptions, SignalLevel)
-
        def onDisconnect(self, Connection):
                Domoticz.Log("onDisconnect called")

@@ -1622,9 +1601,12 @@ def MajDomoDevice(self,DeviceID,Ep,clusterID,value) :
                                        Domoticz.Error("MajDomoDevice - value is not an int = " + str(value) )
                                else:
                                        Domoticz.Debug("MajDomoDevice LvlControl - DvID : " + str(DeviceID) + " - Device EP : " + str(Ep) + " - Value : " + str(sValue) + " sValue : " + str(Devices[x].sValue) )
-
-                                       nValue = 2
-
+                                       if sValue == 0 :
+                                               nValue= 0
+                                       elif sValue == 100 :
+                                               nValue = 1
+                                       else :
+                                               nValue = 2
                                        if str(nValue) != str(Devices[x].nValue) or str(sValue) != str(Devices[x].sValue) :
                                                Domoticz.Debug("MajDomoDevice update DevID : " + str(DeviceID) + " from " + str(Devices[x].nValue) + " to " + str(nValue) )
                                                #UpdateDevice(x, str(nValue), str(sValue) ,DOptions)
@@ -1645,7 +1627,7 @@ def MajDomoDevice(self,DeviceID,Ep,clusterID,value) :
                                                #UpdateDevice(x, str(nValue), str(sValue) ,DOptions)
                                                UpdateDevice_v2(x, str(nValue), str(sValue) ,DOptions, SignalLevel)

-                                               #Modif Meter
+                       #Modif Meter
                        if clusterID=="000c" and Type != "XCube":
                                Domoticz.Debug("Update Value Meter : "+str(round(struct.unpack('f',struct.pack('i',int(value,16)))[0])))
                                `UpdateDevice(x,0,str(round(struct.unpack('f',struct.pack('i',int(value,16)))[0])),DOptions)

**Comment by pipiche38** [comment]
Bon pas glop. Donc les changements que j'ai trouvé trouvés sont:

- onCommand()
- MajDomoDevice


Il y a 2 Domoticz.Debug("TODO!!" ?

**Comment by pipiche38** [comment]
@Smanar peux-tu regarder le PR car à priori tu n'as pas pousser le bon fichier, car voici ce que tu as soumis

```
elif str(StatusCode)=="c6" : StatusMsg="NLME-SYNC.request has failed"
	elif str(StatusCode)=="c7" : StatusMsg="NLME-DIRECT-JOIN.request failure - no space in Router table"
	elif str(StatusCode)=="c8" : StatusMsg="NLME-LEAVE.request failure - device not in Neighbour table"
	elif str(StatusCode)=="c9" : StatusMsg="NLME-GET/SET.request unknown attribute identified"
	elif str(StatusCode)=="ca" : StatusMsg="NLME-JOIN.request detected no networks"
	elif str(StatusCode)=="cb" : StatusMsg="Reserved"
	elif str(StatusCode)=="cc" : StatusMsg="Security processing has failed on outgoing frame due to maximum frame counter"
	elif str(StatusCode)=="cd" : StatusMsg="Security processing has failed on outgoing frame due to no key"
	elif str(StatusCode)=="ce" : StatusMsg="Security processing has failed on outgoing frame due CCM"
	elif str(StatusCode)=="cf" : StatusMsg="Attempt at route discovery has failed due to lack of table space"
	elif str(StatusCode)=="d0" : StatusMsg="Attempt at route discovery has failed due to any reason except lack of table space"
	elif str(StatusCode)=="d1" : StatusMsg="NLDE-DATA.request has failed due to routing failure on sending device"
	elif str(StatusCode)=="d2" : StatusMsg="Broadcast or broadcast-mode multicast has failed as there is no room in BTT"
	elif str(StatusCode)=="d3" : StatusMsg="Unicast mode multi-cast frame was discarded pending route discovery"
	elif str(StatusCode)=="d4" : StatusMsg="Unicast frame does not have a route available but it is buffered for automatic resend"

	elif str(StatusCode)=="a0": StatusMsg="A transmit request failed since the ASDU is too large and fragmentation is not supported"
	elif str(StatusCode)=="a1": StatusMsg="A received fragmented frame could not be defragmented at the current time"
	elif str(StatusCode)=="a2": StatusMsg="A received fragmented frame could not be defragmented since the device does not support fragmentation"
	elif str(StatusCode)=="a3": StatusMsg="A parameter value was out of range"
	elif str(StatusCode)=="a4": StatusMsg="An APSME-UNBIND.request failed due to the requested binding link not existing in the binding table"
	elif str(StatusCode)=="a5": StatusMsg="An APSME-REMOVE-GROUP.request has been issued with a group identified that does not appear in the group table"
	elif str(StatusCode)=="a6": StatusMsg="A parameter value was invaid or out of range"
	elif str(StatusCode)=="a7": StatusMsg="An APSDE-DATA.request requesting ack transmission failed due to no ack being received"
	elif str(StatusCode)=="a8": StatusMsg="An APSDE-DATA.request with a destination addressing mode set to 0x00 failed due to there being no devices bound to this device"
	elif str(StatusCode)=="a9": StatusMsg="An APSDE-DATA.request with a destination addressing mode set to 0x03 failed due to no corresponding short address found in the address map table"
	elif str(StatusCode)=="aa": StatusMsg="An APSDE-DATA.request with a destination addressing mode set to 0x00 failed due to a binding table not being supported on the device"
	elif str(StatusCode)=="ab": StatusMsg="An ASDU was received that was secured using a link key"
	elif str(StatusCode)=="ac": StatusMsg="An ASDU was received that was secured using a network key"
	elif str(StatusCode)=="ad": StatusMsg="An APSDE-DATA.request requesting security has resulted in an error during the corresponding security processing"

	else:                       StatusMsg="Unknown code : " + StatusCode


	return StatusMsg


def removeZigateDevice( self, key ) :
	# remove a device in Zigate
	# Key is the short address of the device
	# extended address is ieee address
	
	if key in  self.ListOfDevices:
		ieee =  self.ListOfDevices[key]['IEEE']
		Domoticz.Log("Remove from Zigate Device = " + str(key) + " IEEE = " +str(ieee) )
		sendZigateCmd("0026", str(ieee) + str(ieee) )
	else :
		Domoticz.Log("Unknow device to be removed - Device  = " + str(key))
		
return
```

**Comment by Smanar** [comment]
Je sais pas ce que j'ai foutu, mais j'ai pas ose trop touche vu qu'il y avait deja un autre pull propose entre les 2 versions.
Deuxieme essais ici https://github.com/sasu-drooz/Domoticz-Zigate/pull/131

**Comment by pipiche38** [comment]
J'ai l'impression que c'est un problème avec les tabulations et les espaces, car sous linux quand je fais un diff -b les différences semblent être cohérentes

**Comment by Smanar** [comment]
Ben la premiere fois, j'ai utilise "replacer tab par espaces et j'ai eu le prb, cette fois c'est "remplacer espace par tab (4 espaces)".
Mais la je galere, dsl pour le brouillon, j'ai le code sur le raspberry et 2 telephones hs (dont un passe a la machine a laver) et je bataille avec la seule prise usb du coin. Donc c'est la version qui tournait hier sur domoticz passe sous pastebin telle quelle sans modifs. Pour la suite, soit je jette un oeuil a ton TODO, soit j'achete un inter zigbee legrand qui fait variateur.

**Comment by pipiche38** [comment]
@Smanar , j'vais me débrouiller pour faire le merge, car de toute façon ca doit etre limité dans onCommand et MajDomoDevice.
Mais il faut que tu puisses y arriver par la suite, car j'ai pas envie de me taper tous les merges avec mes petits doigts potellés ;-)

**Comment by pipiche38** [comment]
Bon, j'ai fait le merge. Ca impact le LvlControl sur les Volets. c'est dans onCommand() il faut que je regarde de plus pret.

**Comment by Smanar** [comment]
Yep, je savais que j'allais pourrir ton code pour les volets, dsl, mais je n'en ai pas donc pas pu tester.
Regardes du cote du "temps de transition", par defaut il etait a 10, j'ai du le passer a 0. Et du cote on/off.

Pour la transition a zero, on peut l'eviter, en fait quand on fait une commande avec une transition a 10 suivie de suite d'une autre commande, la premiere ne se fait pas. Apres est que c'est utile ? Avec la transition a 10 les modifs sur la lampe etaient plus fluides, now ca passe direct de 0% a 100 %.

**Pull request closed without merging**
