### PR TITLE
Update plugin.py

### PR DESCRIPTION
**Pull request by Smanar**
Not full tested yet

### CODE REVIEW

**Comment by pipiche38** [comment]
Can you break this PR into 2. One for the Color Level issue, and one related to the DeviceExist topic ?

**Comment by pipiche38** [comment]
#139 #138 #130 #128

**Comment by Smanar** [comment]
I can, depend of the inpact of my code on your core.

**Comment by pipiche38** [comment]
Any reason why MajDomoDevice got _color removed 

Before:  def MajDomoDevice(self,DeviceID,Ep,clusterID,value,Color_='') :
After : def MajDomoDevice(self,DeviceID,Ep,clusterID,value) :

**Comment by Smanar** [comment]
Yeah, a bad idea. Was because UpdateDevice don't use them but there is an UpdateDevice_v2 in the fonction that need it.
IDK why I haven't bug on my side ...

**Pull request merged**
