### PR TITLE
Code split

### PR DESCRIPTION
**Pull request by Smanar**
Rajout d'une fonction ReadAttributeRequest() qui permet d'obtenir des attributs, possibilite d'en mettre plusieurs (c'est gere par la zigate).

Par exmple : 
z_output.ReadAttributeRequest(self,'17b8', '0000' , '0005')
Rajoute TRADFRI_bulb_E27_CWS_opal_600lm dans 'model'

Je pense que c'est mieux que la manufacture > "IKEA of Sweden", mais sinon le code est presque en place pour la manufacture au cas ou.

Quelques attributs rajoutes en com

Normallement j'ai pris en compte les modifs retreive8Tag(), mais la magie de github ...

### CODE REVIEW

**Comment by Smanar** [comment]
Autre exemple, pour avoir la position d'une lampe, savoir si elle est a on ou off
z_output.ReadAttributeRequest(self,'17b8', '0006' , '0000')

**Comment by zaraki673** [comment]
elif MsgAttrID == "f000" and MsgAttType == "0023" and MsgAttSize == "0004" :

si je ne me trompe pas et me souviens bien :P 
il s'agit du decodage de trame xiaomi des differents capteurs (la trames que j appelle heartbeat)

;)

**Comment by pipiche38** [comment]
the changes in z_domoticz are not related to the comment you made ! So please make a different change. And as far as I'm concerned, this is a needed line, for some devices.

I do also would like to specialize the readattribute() in order to send them accordingly to the device. For instance, you can imagine that for some devices, you want to trigger them more or less often than other.

For instance on the Xiaomi plug, we don't need the ReadAttribute so often, as the device itself is sending status on a very regular basic.
I do not understand why you hardcode the version number in z_var

**Comment by pipiche38** [comment]
@Smanar I found the issue on Firmware Version. In fact it looks like there is a timing issue on the processing of the Firmware decoding.

**Comment by pipiche38** [comment]
I saw an addional Decode8140 function. What is for ? and I didn't see any call to it ?

**Comment by Smanar** [comment]
Versions trop differentes a gerer via github.
Je refais un Pull Propre, mais sans toutes les explications.

**Pull request closed without merging**
