### PR TITLE
Dz storage

### PR DESCRIPTION
**Pull request by pipiche38**
Purpose of this PR is to bring the 1st phase of plugin data storage ( Device, Group, Conf/Settings) on Domoticz database by using the Domoticz.Configuration() API available as of 2021.1

In this 1st stage, 

to enable the Dz storage, this need to be activated "useDomoticzDatabase" in the Experimental advanced setting

in addition to filesystem storage ( DeviceList-xx.txt, GroupList-xx.json, PluginConf-xx.json ), the storage will happen in the Domoticz Database. The following schema is current used:

```
{ 'PluginConf': { 'TimeStamp': time of storage, 'Settings': <the all settings> }}
{ 'ListOfGroups':  { 'TimeStamp': time of storage, 'Groups': <all groups>}}
{ 'ListOfDevices': { 'TimeStamp': time of storage, 'ListOfDevices': <all devices>}}
```

When loading the files, a check will be run against the filesystem storage, and the normal storage will be used in ALL cases.
However differences might be reported

In 2nd stage, the approach will be use the TimeStamp and to verify against the normal filesystem storage. In case the filesystem storage is newer then this one will be used. This will allow:
 1. going back and forth during the testing
 2. for Settings, giving the possibility to overwrite some parameters

### CODE REVIEW

**Comment by pipiche38** [comment]
For now testing regression without enabling the feature

**Comment by jp-keros** [comment]
useDomoticzDatabase checked on my test domoticz setup running a ZiGate V2. 
Nothing special after restarting the plugin.

**Comment by pipiche38** [comment]
24 hours on production .. regression tests seems ok. I have now enabled the usedomoticzDatabase . on going for 24 hours

**Comment by pipiche38** [comment]
Few changes implemented in the recent commit.

DeviceList is now stored in b64encoding to solve several issues ( null embedded char, None value )
Version Attribute is also set to 1 in order to be able to handle any storage changes in the future

**Pull request merged**
